### ISSUE TITLE
Crash on start with the recommended config

### ISSUE THREAD

**Issue by Yodzorah** [paul-nameless/tg#128]
# Doesn't work

In `conf.py`:

```
#LOG_LEVEL = "DEBUG"
LOG_PATH = "~/.local/share/tg/"
```

Which gives me on `tg` start:

```
Traceback (most recent call last):
  File "/usr/bin/tg", line 11, in <module>
    load_entry_point('tg==0.3.0', 'console_scripts', 'tg')()
  File "/usr/lib/python3.8/site-packages/tg/main.py", line 59, in main
    utils.setup_log()
  File "/usr/lib/python3.8/site-packages/tg/utils.py", line 58, in setup_log
    handler = RotatingFileHandler(
  File "/usr/lib/python3.8/logging/handlers.py", line 148, in __init__
    BaseRotatingHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.8/logging/handlers.py", line 55, in __init__
    logging.FileHandler.__init__(self, filename, mode, encoding, delay)
  File "/usr/lib/python3.8/logging/__init__.py", line 1143, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.8/logging/__init__.py", line 1172, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/username/~/.local/share/tg/all.log'
```

# Works

In `conf.py`:

```
#LOG_LEVEL = "DEBUG"
LOG_PATH = "/home/username/.local/share/tg/"
```

Which makes `tg` behave as expected.

**Comment by paul-nameless** [comment]
The idea was to use it this way:
```
import os
os.path.expanduser("~/.local/share/tg/")
```
But apparently I can see that it's not very obvious so we will change the behavior.

**Comment by Yodzorah** [comment]
@paul-nameless, ok, seems like a good idea, but right now there's also a problem with the recommended configuration in `readme.md`:

```python
...
# log level for debugging, info by default
LOG_LEVEL = "DEBUG"
# path where logs will be stored (all.log and error.log)
LOG_PATH = "~/.local/share/tg/"
...
```

**Comment by paul-nameless** [comment]
Yeah, you right. Should be updated, thanks.

**Comment by paul-nameless** [comment]
For now that's all changes will make for now.
