### ISSUE TITLE
Jump to reply message only works for tg generated replies

### ISSUE THREAD

**Issue by matheusfillipe** [paul-nameless/tg#192]
Is that not yet implemented? Hitting 'm' on a reply message that was created on another telegram client does not as expected, moving to the original message, while it still goes fine if the reply was generated on tg. 

I am on 2bd0fcb.

**Comment by paul-nameless** [comment]
Can't reproduce. Does it matter if you will reply or somebody else?
Can you check the logs, maybe there are errors.

**Comment by matheusfillipe** [comment]
This is the error that happens when I press 'm' on some chat. It works on other chats though, but this is a private chat I get like a lot of messages on (like 50 before replying, about that, not sure what else could be specific about it) .  This is trying to "m" a message that I replied on telegram desktop GUI client. 
```
==> /home/matheus/.local/share/tg/error.log <==
ERROR [2020-11-26 22:56:11,899] controllers.py:776 - handle | Error happend in key handle loop
Traceback (most recent call last):
  File "/home/matheus/.local/lib/python3.8/site-packages/tg/controllers.py", line 770, in handle
    res = fun(self, repeat_factor)  # type: ignore
  File "/home/matheus/.local/lib/python3.8/site-packages/tg/controllers.py", line 56, in _no_repeat_factor
    return fun(self)
  File "/home/matheus/.local/lib/python3.8/site-packages/tg/controllers.py", line 188, in jump_to_reply_msg
    if not self.model.msgs.jump_to_msg_by_id(chat_id, msg.reply_msg_id):
  File "/home/matheus/.local/lib/python3.8/site-packages/tg/models.py", line 494, in jump_to_msg_by_id
    if index := self.msg_ids[chat_id].index(msg_id):
ValueError: 488327086080 is not in list

```
Another weird thing I noticed about this is that I can't select the message that I replied to on the tg TUI anymore, it just skips it and starts really screwing up the selection (The messages are displayed but I can't select them).


```
ERROR [2020-11-26 23:02:28,415] controllers.py:807 - draw | Error happened in draw loop
Traceback (most recent call last):
  File "/home/matheus/.local/lib/python3.8/site-packages/tg/controllers.py", line 805, in draw
    fun()
  File "/home/matheus/.local/lib/python3.8/site-packages/tg/controllers.py", line 857, in _render_msgs
    self.view.msgs.draw(
  File "/home/matheus/.local/lib/python3.8/site-packages/tg/views.py", line 530, in draw
    self.win.addstr(line_num, column, elem, attr)
_curses.error: addwstr() returned ERR
ERROR [2020-11-26 23:02:31,129] controllers.py:807 - draw | Error happened in draw loop
Traceback (most recent call last):
  File "/home/matheus/.local/lib/python3.8/site-packages/tg/controllers.py", line 805, in draw
    fun()
  File "/home/matheus/.local/lib/python3.8/site-packages/tg/controllers.py", line 857, in _render_msgs
    self.view.msgs.draw(
  File "/home/matheus/.local/lib/python3.8/site-packages/tg/views.py", line 530, in draw
    self.win.addstr(line_num, column, elem, attr)
_curses.error: addwstr() returned ERR



ERROR [2020-11-26 23:02:41,531] controllers.py:807 - draw | Error happened in draw loop
Traceback (most recent call last):
  File "/home/matheus/.local/lib/python3.8/site-packages/tg/controllers.py", line 805, in draw
    fun()
  File "/home/matheus/.local/lib/python3.8/site-packages/tg/controllers.py", line 857, in _render_msgs
    self.view.msgs.draw(
  File "/home/matheus/.local/lib/python3.8/site-packages/tg/views.py", line 530, in draw
    self.win.addstr(line_num, column, elem, attr)
_curses.error: addwstr() returned ERR
ERROR [2020-11-26 23:02:46,975] controllers.py:807 - draw | Error happened in draw loop
Traceback (most recent call last):
  File "/home/matheus/.local/lib/python3.8/site-packages/tg/controllers.py", line 805, in draw
    fun()
  File "/home/matheus/.local/lib/python3.8/site-packages/tg/controllers.py", line 857, in _render_msgs
    self.view.msgs.draw(
  File "/home/matheus/.local/lib/python3.8/site-packages/tg/views.py", line 530, in draw
    self.win.addstr(line_num, column, elem, attr)
_curses.error: addwstr() returned ERR

```
Oh another detail is that I am replying to a message that is already a reply (Sorry I am pretty sure this probrably doesn't matter but I have no clue what is specific about that chat 😅).

And as I am writing this and testing it just worked but it is now walking every 2 messages on this chat haha, and no error message, even if I restart tg.
