### ISSUE TITLE
tg doesn't work on python 3.9

### ISSUE THREAD

**Issue by nexagenom** [paul-nameless/tg#206]
`
ERROR [2021-02-21 14:57:25,811] update_handlers.py:32 - wrapper | Error happened in handler: updateNewChat
Traceback (most recent call last):
  File "/home/michael/.local/lib/python3.9/site-packages/tg/update_handlers.py", line 30, in wrapper
    fun(controller, update)
  File "/home/michael/.local/lib/python3.9/site-packages/tg/update_handlers.py", line 119, in update_new_chat
    controller.model.chats.add_chat(chat)
  File "/home/michael/.local/lib/python3.9/site-packages/tg/models.py", line 439, in add_chat
    if int(chat["order"]) == 0:
KeyError: 'order'
ERROR [2021-02-21 14:57:25,811] update_handlers.py:32 - wrapper | Error happened in handler: updateChatLastMessage
Traceback (most recent call last):
  File "/home/michael/.local/lib/python3.9/site-packages/tg/update_handlers.py", line 30, in wrapper
    fun(controller, update)
  File "/home/michael/.local/lib/python3.9/site-packages/tg/update_handlers.py", line 192, in update_chat_last_message
    order = update["order"]
KeyError: 'order'
ERROR [2021-02-21 14:57:26,614] controllers.py:807 - draw | Error happened in draw loop
Traceback (most recent call last):
  File "/home/michael/.local/lib/python3.9/site-packages/tg/controllers.py", line 805, in draw
    fun()
  File "/home/michael/.local/lib/python3.9/site-packages/tg/controllers.py", line 798, in _resize
    self._render()
  File "/home/michael/.local/lib/python3.9/site-packages/tg/controllers.py", line 825, in _render
    self._render_chats()
  File "/home/michael/.local/lib/python3.9/site-packages/tg/controllers.py", line 836, in _render_chats
    chats = self.model.get_chats(
  File "/home/michael/.local/lib/python3.9/site-packages/tg/models.py", line 160, in get_chats
    return self.chats.fetch_chats(offset=offset, limit=limit)
  File "/home/michael/.local/lib/python3.9/site-packages/tg/models.py", line 392, in fetch_chats
    self._load_next_chats()
  File "/home/michael/.local/lib/python3.9/site-packages/tg/models.py", line 424, in _load_next_chats
    self.add_chat(chat)
  File "/home/michael/.local/lib/python3.9/site-packages/tg/models.py", line 439, in add_chat
    if int(chat["order"]) == 0:
KeyError: 'order'
`

Getting this error when using Python 3.9, terminal showing only black screen.

**Comment by paul-nameless** [comment]
Duplicates https://github.com/paul-nameless/tg/issues/180
