### ISSUE TITLE
KeyError: 'positions' on updateChatLastMessage

### ISSUE THREAD

**Issue by jugendhacker** [paul-nameless/tg#215]
I'm reporting this for a user, who does not have a github account.

The log of this user fills up with the following traces quite fast. Looks like it might be related to libtd version differences but I'm not totally sure.

```
ERROR [2021-04-21 17:23:18,769] update_handlers.py:32 - wrapper | Error happened in handler: updateChatLastMessage
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/tg/update_handlers.py", line 30, in wrapper
    fun(controller, update)
  File "/usr/lib/python3.9/site-packages/tg/update_handlers.py", line 210, in update_chat_last_message
    if len(update["positions"]) > 0:
KeyError: 'positions'
ERROR [2021-04-21 17:23:18,770] update_handlers.py:32 - wrapper | Error happened in handler: updateChatLastMessage
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/tg/update_handlers.py", line 30, in wrapper
    fun(controller, update)
  File "/usr/lib/python3.9/site-packages/tg/update_handlers.py", line 210, in update_chat_last_message
    if len(update["positions"]) > 0:
KeyError: 'positions'
ERROR [2021-04-21 17:23:18,772] controllers.py:803 - draw | Error happened in draw loop
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/tg/controllers.py", line 801, in draw
    fun()
  File "/usr/lib/python3.9/site-packages/tg/controllers.py", line 832, in _render_chats
    chats = self.model.get_chats(
  File "/usr/lib/python3.9/site-packages/tg/models.py", line 160, in get_chats
    return self.chats.fetch_chats(offset=offset, limit=limit)
  File "/usr/lib/python3.9/site-packages/tg/models.py", line 393, in fetch_chats
    self._load_next_chats()
  File "/usr/lib/python3.9/site-packages/tg/models.py", line 425, in _load_next_chats
    self.add_chat(chat)
  File "/usr/lib/python3.9/site-packages/tg/models.py", line 441, in add_chat
    if len(chat["positions"]) > 0:
KeyError: 'positions'
```

**Comment by jamesponddotco** [comment]
Same error on my end. Running an up-to-date version of Ubuntu 20.04 with Python 3.8.5, and an up-to-date version of tg, I get the error above and nothing shows up.

However, it does work again when I compile TDLib from their Git repository and point `TDLIB_PATH` to the updated version.

**Comment by jugendhacker** [comment]
Okay so by explicitly setting the TDLIB_PATH it also worked for the user I'm reporting for. So this seems a setup specific problem, because the Arch package of python-telegram uses the system tdlib and selects the wrong libtd on runtime... strange.... gets even more strange because in a `python3` shell, it selects the right libtd version...

**Comment by paul-nameless** [comment]
This should be resolved in newer versions as we updated python-telegram and it ships tdlib 1.7.0
