### ISSUE TITLE
No text shown in quick msg bottom line

### ISSUE THREAD

**Issue by JingMatrix** [paul-nameless/tg#216]
When I type start with `i`, my cursor moves, but no text is shown there.

It is due to following error, I was typing the word `yes`:

```
Traceback (most recent call last):
  File "/home/jing/.local/lib/python3.9/site-packages/tg/views.py", line 39, in addstr
    return self.win.addstr(y, x, _str, attr)
TypeError: an integer is required (got type NoneType)
ERROR [2021-04-22 18:28:10,333] views.py:41 - addstr | Error drawing: y=0, x=0, _str='y', attr=None
Traceback (most recent call last):
  File "/home/jing/.local/lib/python3.9/site-packages/tg/views.py", line 39, in addstr
    return self.win.addstr(y, x, _str, attr)
TypeError: an integer is required (got type NoneType)
ERROR [2021-04-22 18:28:10,479] views.py:41 - addstr | Error drawing: y=0, x=0, _str='ye', attr=None
Traceback (most recent call last):
  File "/home/jing/.local/lib/python3.9/site-packages/tg/views.py", line 39, in addstr
    return self.win.addstr(y, x, _str, attr)
TypeError: an integer is required (got type NoneType)
ERROR [2021-04-22 18:28:10,758] views.py:41 - addstr | Error drawing: y=0, x=0, _str='yes', attr=None
Traceback (most recent call last):
  File "/home/jing/.local/lib/python3.9/site-packages/tg/views.py", line 39, in addstr
    return self.win.addstr(y, x, _str, attr)
TypeError: an integer is required (got type NoneType)
```

**Comment by JingMatrix** [comment]
In this line, please change `Any = None` to `Any = 0`:
https://github.com/paul-nameless/tg/blob/bba72ef534f99422820eb46748804df18063b202/tg/views.py#L37

**Comment by paul-nameless** [comment]
Thanks, fixed
