### ISSUE TITLE
musl support

### ISSUE THREAD

**Issue by faustri** [paul-nameless/tg#238]
Is it possible to get tg to work on a musl system like alpine linux?
```
>  /4/.local/bin/tg
find: ‘/4/.cache/tg/files’: No such file or directory
Traceback (most recent call last):
  File "/4/.local/bin/tg", line 8, in <module>
    sys.exit(main())
  File "/4/.local/lib/python3.9/site-packages/tg/__main__.py", line 60, in main
    tg = Tdlib(
  File "/4/.local/lib/python3.9/site-packages/telegram/client.py", line 130, in __init__
    self._tdjson = TDJson(library_path=library_path, verbosity=tdlib_verbosity)
  File "/4/.local/lib/python3.9/site-packages/telegram/tdjson.py", line 27, in __init__
    self._build_client(library_path, verbosity)
  File "/4/.local/lib/python3.9/site-packages/telegram/tdjson.py", line 36, in _build_client
    self._tdjson = CDLL(library_path)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
```

**Comment by jugendhacker** [comment]
I'm currently working on packaging tg for alpine. But the error does not look like it's caused by musl.

**Comment by faustri** [comment]
That's great, I guess I'll just close this issue then, thanks!
