### ISSUE TITLE
update telegram-tg

### ISSUE THREAD

**Issue by 0x3n0** [paul-nameless/tg#257]
Traceback (most recent call last):
  File "/sbin/tg", line 33, in <module>
    sys.exit(load_entry_point('tg==0.17.0', 'console_scripts', 'tg')())
  File "/sbin/tg", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for tg

**Comment by Eloitor** [comment]
Hi,
I'm an alpine linux user. Running `tg` gives me this error: https://pastebin.com/n0nXF6mb
It seems that in alpine's repos there is py3-telegram version 0.16.0 available: https://pkgs.alpinelinux.org/package/edge/testing/x86_64/py3-telegram but the version required for tg is 0.15.0: https://github.com/paul-nameless/tg/blob/master/setup.py#L26

**Comment by jugendhacker** [comment]
@Eloitor first of all: please report distro specific issues upstream first, in this case it would be https://gitlab.alpinelinux.org/alpine/aports/-/issues

Second: thanks for the hint, I uploaded a patch to aports, it just needs to be merged

**Comment by Eloitor** [comment]
thank you for the effort!

I wasn't sure if version 0.16.0 was supported. When a program has a pinned version, sometimes is for some good reason. Also, I think the right place to change this is in this repo.

**Comment by jugendhacker** [comment]
@Eloitor the right place to finally change this, might be here, yes. But this was clearly a downstream issue on the Alpine end, as we upgraded python-telegram while the package for tg was still pinning/requiring an older version, so please report it downstream, so package maitainers could figure out how to fix the packages and work with upstream to get this maybe fixed for everyone. Because if every downstream issue would be reported directly upstream, it's just a lot of spam for the developers here, with stuff that is often not even caused by them
