### ISSUE TITLE
Chat and messages are not rendering

### ISSUE THREAD

**Issue by drednoot** [paul-nameless/tg#260]
Using arch
Installed from AUR
I was able to enter my phone number, then everything just dissappeared
log file is just spammed with this
```
ERROR [2022-01-23 22:56:42,831] controllers.py:807 - draw | Error happened in draw loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/tg/controllers.py", line 805, in draw
    fun()
  File "/usr/lib/python3.10/site-packages/tg/controllers.py", line 825, in _render
    self._render_chats()
  File "/usr/lib/python3.10/site-packages/tg/controllers.py", line 842, in _render_chats
    self.view.chats.draw(selected_chat, chats, self.model.chats.title)
  File "/usr/lib/python3.10/site-packages/tg/views.py", line 216, in draw
    last_msg_sender, last_msg = self._get_last_msg_data(chat)
  File "/usr/lib/python3.10/site-packages/tg/views.py", line 249, in _get_last_msg_data
    user, last_msg = get_last_msg(chat, self.model.users)
  File "/usr/lib/python3.10/site-packages/tg/views.py", line 613, in get_last_msg
    last_msg["sender_id"].get("user_id"),
KeyError: 'sender_id'
```

**Comment by jugendhacker** [comment]
Did you upgrade the AUR package? I patched it, so it should work again....

**Comment by drednoot** [comment]
Yeah, works now. Thanks

**Comment by prog666** [comment]
I get same issue on mac, installed with homebrew, installation with pip3 doesn't work on apple silicon (getting error about some libtdjson.dylib not being available for arm64e

**Comment by edganiukov** [comment]
I see the same error on void linux. 
@jugendhacker can you tell exactly what did you fix?
