### ISSUE TITLE
No output in tg unless I'm root

### ISSUE THREAD

**Issue by dolphinau** [paul-nameless/tg#264]
Hi, I've recently started using tg and it appears that I can't use it unless I launch `sudo tg`, which is boring because I didn't want to soil my /root directory.
When I just launch `tg`, the client is running, but I just have a black screen in my terminal. 
I tried to press random keys on my keyboard and it appears that I have control over the client, I mean I can select a conversation, send messages but I have no output from it.

![image](https://user-images.githubusercontent.com/27704776/159163981-e9045423-9153-44ff-a7da-9a93803846af.png)

I tried on several Window Manager (plasma and qtile) but none of them solved my issue.

I don't know what information could be useful for you, I'm using arcolinux, and I installed tg via the aur/telegram-tg-git package.
Any ideas? Maybe I miss one permission I don't know what could go wrong...

**Comment by z8512** [comment]
Same issue after I built tdlib from latest source code

**Comment by lumipixi** [comment]
I installed tg from the AUR. After compiling, I'm having the same problem in Arch Linux, but not Manjaro.

Here's what ~/.local/share/tg/error.log shows. This appears to repeat every time the client tries to draw something because I have a few thousand lines like these.

```
ERROR [2022-03-26 14:15:45,937] controllers.py:807 - draw | Error happened in draw loop
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/tg/controllers.py", line 805, in draw
    fun()
  File "/usr/lib/python3.10/site-packages/tg/controllers.py", line 798, in _resize
    self._render()
  File "/usr/lib/python3.10/site-packages/tg/controllers.py", line 825, in _render
    self._render_chats()
  File "/usr/lib/python3.10/site-packages/tg/controllers.py", line 842, in _render_chats
    self.view.chats.draw(selected_chat, chats, self.model.chats.title)
  File "/usr/lib/python3.10/site-packages/tg/views.py", line 216, in draw
    last_msg_sender, last_msg = self._get_last_msg_data(chat)
  File "/usr/lib/python3.10/site-packages/tg/views.py", line 249, in _get_last_msg_data
    user, last_msg = get_last_msg(chat, self.model.users)
  File "/usr/lib/python3.10/site-packages/tg/views.py", line 613, in get_last_msg
    last_msg["sender_id"].get("user_id"),
```

**Comment by kchebes** [comment]
Same issue here on MacOS. The messages are being sent but unfortunately I can't see anything that I'm doing. 
Both tg and tdlib are freshly brewed and updated to latest versions :(

**Comment by kchebes** [comment]
Sorry for the slight change of topic but I have to ask about the link to the wallpaper @atxr 😅

**Comment by kchebes** [comment]
Thank you very much mate! @atxr

**Comment by ahanniga** [comment]
Same, blank screen on MacOS :-(

**Comment by sozoalvin** [comment]
just want to say that - i installed from master and ensured master was updated with the new merged but still have the same draw line errors.. is there anything i can do to help?

**Comment by polemon** [comment]
Just installed from sources and it doesn't work. Terminal emulator is all blank.

**Comment by sozoalvin** [comment]
@polemon set tdlib in with the correct paths in the config py

**Comment by polemon** [comment]
> @polemon set tdlib in with the correct paths in the config py

Thanks! That helped!
Perhaps the doc/readme should mention it's `libtdjson.so` (or rather one of the versioned files) should be put into `TDLIB_PATH`, I kinda had to trial end error that...
