### ISSUE TITLE
Check `have_dialog(dialog_id)` failed

### ISSUE THREAD

**Issue by Neykuratick** [paul-nameless/tg#268]
Hello, the app crashes. I tried reinstalling, but it didn't work

Whenever i run ``` tg ``` in my terminal, it crushes with these messages:
- ``` Check `have_dialog(dialog_id)` failed ```
- ``` zsh: segmentation fault (core dumped)  tg ```

**Comment by Neykuratick** [comment]
ERROR [2022-04-16 14:52:30,926] update_handlers.py:32 - wrapper | Error happened in handler: updateNewMessage
Traceback (most recent call last):
  File "/home/roman/.local/lib/python3.10/site-packages/tg/update_handlers.py", line 30, in wrapper
    fun(controller, update)
  File "/home/roman/.local/lib/python3.10/site-packages/tg/update_handlers.py", line 76, in update_new_message
    if msg.file_id and msg.size and msg.size <= max_download_size:
  File "/home/roman/.local/lib/python3.10/site-packages/tg/msg.py", line 118, in file_id
    return doc["id"]
KeyError: 'id'
ERROR [2022-04-16 14:52:30,932] update_handlers.py:32 - wrapper | Error happened in handler: updateNewMessage
Traceback (most recent call last):
  File "/home/roman/.local/lib/python3.10/site-packages/tg/update_handlers.py", line 30, in wrapper
    fun(controller, update)
  File "/home/roman/.local/lib/python3.10/site-packages/tg/update_handlers.py", line 76, in update_new_message
    if msg.file_id and msg.size and msg.size <= max_download_size:
  File "/home/roman/.local/lib/python3.10/site-packages/tg/msg.py", line 118, in file_id
    return doc["id"]
KeyError: 'id'
ERROR [2022-04-16 14:53:24,368] update_handlers.py:32 - wrapper | Error happened in handler: updateNewMessage
Traceback (most recent call last):
  File "/home/roman/.local/lib/python3.10/site-packages/tg/update_handlers.py", line 30, in wrapper
    fun(controller, update)
  File "/home/roman/.local/lib/python3.10/site-packages/tg/update_handlers.py", line 76, in update_new_message
    if msg.file_id and msg.size and msg.size <= max_download_size:
  File "/home/roman/.local/lib/python3.10/site-packages/tg/msg.py", line 118, in file_id
    return doc["id"]
KeyError: 'id'
ERROR [2022-04-16 14:53:24,368] update_handlers.py:32 - wrapper | Error happened in handler: updateNewMessage
Traceback (most recent call last):
  File "/home/roman/.local/lib/python3.10/site-packages/tg/update_handlers.py", line 30, in wrapper
    fun(controller, update)
  File "/home/roman/.local/lib/python3.10/site-packages/tg/update_handlers.py", line 76, in update_new_message
    if msg.file_id and msg.size and msg.size <= max_download_size:
  File "/home/roman/.local/lib/python3.10/site-packages/tg/msg.py", line 118, in file_id
    return doc["id"]
KeyError: 'id'
ERROR [2022-04-16 14:53:50,037] update_handlers.py:32 - wrapper | Error happened in handler: updateNewMessage
Traceback (most recent call last):
  File "/home/roman/.local/lib/python3.10/site-packages/tg/update_handlers.py", line 30, in wrapper
    fun(controller, update)
  File "/home/roman/.local/lib/python3.10/site-packages/tg/update_handlers.py", line 76, in update_new_message
    if msg.file_id and msg.size and msg.size <= max_download_size:
  File "/home/roman/.local/lib/python3.10/site-packages/tg/msg.py", line 118, in file_id
    return doc["id"]
KeyError: 'id'
ERROR [2022-04-16 14:53:50,040] update_handlers.py:32 - wrapper | Error happened in handler: updateNewMessage
Traceback (most recent call last):
  File "/home/roman/.local/lib/python3.10/site-packages/tg/update_handlers.py", line 30, in wrapper
    fun(controller, update)
  File "/home/roman/.local/lib/python3.10/site-packages/tg/update_handlers.py", line 76, in update_new_message
    if msg.file_id and msg.size and msg.size <= max_download_size:
  File "/home/roman/.local/lib/python3.10/site-packages/tg/msg.py", line 118, in file_id
    return doc["id"]
KeyError: 'id'
ERROR [2022-04-16 14:57:48,503] controllers.py:807 - draw | Error happened in draw loop
Traceback (most recent call last):
  File "/home/roman/.local/lib/python3.10/site-packages/tg/controllers.py", line 805, in draw
    fun()
  File "/home/roman/.local/lib/python3.10/site-packages/tg/controllers.py", line 842, in _render_chats
    self.view.chats.draw(selected_chat, chats, self.model.chats.title)
  File "/home/roman/.local/lib/python3.10/site-packages/tg/views.py", line 205, in draw
    self.win.vline(0, width, line, self.h)
_curses.error: wmove() returned ERR
ERROR [2022-04-16 14:57:51,395] update_handlers.py:32 - wrapper | Error happened in handler: updateNewMessage
Traceback (most recent call last):
  File "/home/roman/.local/lib/python3.10/site-packages/tg/update_handlers.py", line 30, in wrapper
    fun(controller, update)
  File "/home/roman/.local/lib/python3.10/site-packages/tg/update_handlers.py", line 76, in update_new_message
    if msg.file_id and msg.size and msg.size <= max_download_size:
  File "/home/roman/.local/lib/python3.10/site-packages/tg/msg.py", line 118, in file_id
    return doc["id"]
KeyError: 'id'
ERROR [2022-04-16 14:57:51,406] update_handlers.py:32 - wrapper | Error happened in handler: updateNewMessage
Traceback (most recent call last):
  File "/home/roman/.local/lib/python3.10/site-packages/tg/update_handlers.py", line 30, in wrapper
    fun(controller, update)
  File "/home/roman/.local/lib/python3.10/site-packages/tg/update_handlers.py", line 76, in update_new_message
    if msg.file_id and msg.size and msg.size <= max_download_size:
  File "/home/roman/.local/lib/python3.10/site-packages/tg/msg.py", line 118, in file_id
    return doc["id"]
KeyError: 'id'
ERROR [2022-04-16 14:58:04,799] controllers.py:807 - draw | Error happened in draw loop
Traceback (most recent call last):
  File "/home/roman/.local/lib/python3.10/site-packages/tg/controllers.py", line 805, in draw
    fun()
  File "/home/roman/.local/lib/python3.10/site-packages/tg/controllers.py", line 842, in _render_chats
    self.view.chats.draw(selected_chat, chats, self.model.chats.title)
  File "/home/roman/.local/lib/python3.10/site-packages/tg/views.py", line 205, in draw
    self.win.vline(0, width, line, self.h)
_curses.error: wmove() returned ERR
ERROR [2022-04-16 14:58:07,763] controllers.py:807 - draw | Error happened in draw loop
Traceback (most recent call last):
  File "/home/roman/.local/lib/python3.10/site-packages/tg/controllers.py", line 805, in draw
    fun()
  File "/home/roman/.local/lib/python3.10/site-packages/tg/controllers.py", line 842, in _render_chats
    self.view.chats.draw(selected_chat, chats, self.model.chats.title)
  File "/home/roman/.local/lib/python3.10/site-packages/tg/views.py", line 205, in draw
    self.win.vline(0, width, line, self.h)
_curses.error: wmove() returned ERR
ERROR [2022-04-16 14:58:09,132] controllers.py:807 - draw | Error happened in draw loop
Traceback (most recent call last):
  File "/home/roman/.local/lib/python3.10/site-packages/tg/controllers.py", line 805, in draw
    fun()
  File "/home/roman/.local/lib/python3.10/site-packages/tg/controllers.py", line 842, in _render_chats
    self.view.chats.draw(selected_chat, chats, self.model.chats.title)
  File "/home/roman/.local/lib/python3.10/site-packages/tg/views.py", line 205, in draw
    self.win.vline(0, width, line, self.h)
_curses.error: wmove() returned ERR
ERROR [2022-04-16 14:58:15,572] controllers.py:807 - draw | Error happened in draw loop
Traceback (most recent call last):
  File "/home/roman/.local/lib/python3.10/site-packages/tg/controllers.py", line 805, in draw
    fun()
  File "/home/roman/.local/lib/python3.10/site-packages/tg/controllers.py", line 842, in _render_chats
    self.view.chats.draw(selected_chat, chats, self.model.chats.title)
  File "/home/roman/.local/lib/python3.10/site-packages/tg/views.py", line 205, in draw
    self.win.vline(0, width, line, self.h)
_curses.error: wmove() returned ERR
ERROR [2022-04-16 14:58:19,179] controllers.py:807 - draw | Error happened in draw loop
Traceback (most recent call last):
  File "/home/roman/.local/lib/python3.10/site-packages/tg/controllers.py", line 805, in draw
    fun()
  File "/home/roman/.local/lib/python3.10/site-packages/tg/controllers.py", line 842, in _render_chats
    self.view.chats.draw(selected_chat, chats, self.model.chats.title)
  File "/home/roman/.local/lib/python3.10/site-packages/tg/views.py", line 205, in draw
    self.win.vline(0, width, line, self.h)
_curses.error: wmove() returned ERR

**Comment by Neykuratick** [comment]
I figured out it was a bug in tglib. denis-gordeev fixed it in [this PR](https://github.com/paul-nameless/tg/pull/267)

just clone it and install

**Comment by paul-nameless** [comment]
Thanks for the info!
