### ISSUE TITLE
Authentication fails.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [paul-nameless/tg#275]
```
[root@BEEDELLROKEJULIANLOCKHART /]# pip3 install tg
Collecting tg
  Downloading tg-0.19.0-py3-none-any.whl (73 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.6/73.6 KB 96.0 kB/s eta 0:00:00
Collecting python-telegram==0.15.0
  Downloading python-telegram-0.15.0.tar.gz (14.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.9/14.9 MB 63.3 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for python-telegram, since package 'wheel' is not installed.
Installing collected packages: python-telegram, tg
  Running setup.py install for python-telegram ... done
Successfully installed python-telegram-0.15.0 tg-0.19.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[root@BEEDELLROKEJULIANLOCKHART /]# exit
exit
Script done.
[root@BEEDELLROKEJULIANLOCKHART /]# tg
Enter your phone number in international format (including country code)
phone> +447840875616
find: ‘/root/.cache/tg/files’: No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/tg", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/tg/__main__.py", line 60, in main
    tg = Tdlib(
  File "/usr/local/lib/python3.10/site-packages/telegram/client.py", line 136, in __init__
    self._tdjson = TDJson(library_path=library_path, verbosity=tdlib_verbosity)
  File "/usr/local/lib/python3.10/site-packages/telegram/tdjson.py", line 27, in __init__
    self._build_client(library_path, verbosity)
  File "/usr/local/lib/python3.10/site-packages/telegram/tdjson.py", line 34, in _build_client
    self._tdjson = CDLL(library_path)
  File "/usr/lib64/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libssl.so.1.1: cannot open shared object file: No such file or directory
[root@BEEDELLROKEJULIANLOCKHART /]# su
[root@BEEDELLROKEJULIANLOCKHART /]# exit
exit
[root@BEEDELLROKEJULIANLOCKHART /]# exit
exit
[BEEDELLROKEJULIANLOCKHART@BEEDELLROKEJULIANLOCKHART /]$ tg
Enter your phone number in international format (including country code)
phone> +447840875616
find: ‘/home/BEEDELLROKEJULIANLOCKHART/.cache/tg/files’: No such file or directory
Traceback (most recent call last):
  File "/usr/local/bin/tg", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/tg/__main__.py", line 60, in main
    tg = Tdlib(
  File "/usr/local/lib/python3.10/site-packages/telegram/client.py", line 136, in __init__
    self._tdjson = TDJson(library_path=library_path, verbosity=tdlib_verbosity)
  File "/usr/local/lib/python3.10/site-packages/telegram/tdjson.py", line 27, in __init__
    self._build_client(library_path, verbosity)
  File "/usr/local/lib/python3.10/site-packages/telegram/tdjson.py", line 34, in _build_client
    self._tdjson = CDLL(library_path)
  File "/usr/lib64/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libssl.so.1.1: cannot open shared object file: No such file or directory
[BEEDELLROKEJULIANLOCKHART@BEEDELLROKEJULIANLOCKHART /]$
```

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
I believe that the similarity of this problem to "https://gitlab.com/postmarketOS/pmbootstrap/-/issues/2127" may demonstrate that pip is operating erroneously. Are you able to confirm this?

```
[BEEDELLROKEJULIANLOCKHART@BEEDELLROKEJULIANLOCKHART /]$ su
[root@BEEDELLROKEJULIANLOCKHART /]# script -a
Script started, output log file is 'typescript'.
[root@BEEDELLROKEJULIANLOCKHART /]# pip uninstall tg
Found existing installation: tg 0.19.0
Uninstalling tg-0.19.0:
  Would remove:
    /usr/local/bin/tg
    /usr/local/lib/python3.10/site-packages/tg-0.19.0.dist-info/*
    /usr/local/lib/python3.10/site-packages/tg/*
Proceed (Y/n)? Y
  Successfully uninstalled tg-0.19.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[root@BEEDELLROKEJULIANLOCKHART /]# exit
exit
Script done.
[root@BEEDELLROKEJULIANLOCKHART /]# exit
exit
[BEEDELLROKEJULIANLOCKHART@BEEDELLROKEJULIANLOCKHART /]$ pip install tg
Defaulting to user installation because normal site-packages is not writeable
Collecting tg
  Downloading tg-0.19.0-py3-none-any.whl (73 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.6/73.6 KB 144.2 kB/s eta 0:00:00
Requirement already satisfied: python-telegram==0.15.0 in /usr/local/lib/python3.10/site-packages (from tg) (0.15.0)
Installing collected packages: tg
Successfully installed tg-0.19.0
[BEEDELLROKEJULIANLOCKHART@BEEDELLROKEJULIANLOCKHART /]$ pip uninstall tg
Found existing installation: tg 0.19.0
Uninstalling tg-0.19.0:
  Would remove:
    /home/BEEDELLROKEJULIANLOCKHART/.local/bin/tg
    /home/BEEDELLROKEJULIANLOCKHART/.local/lib/python3.10/site-packages/tg-0.19.0.dist-info/*
    /home/BEEDELLROKEJULIANLOCKHART/.local/lib/python3.10/site-packages/tg/*
Proceed (Y/n)? Y
  Successfully uninstalled tg-0.19.0
[BEEDELLROKEJULIANLOCKHART@BEEDELLROKEJULIANLOCKHART /]$ pip3 install tg
Defaulting to user installation because normal site-packages is not writeable
Collecting tg
  Using cached tg-0.19.0-py3-none-any.whl (73 kB)
Requirement already satisfied: python-telegram==0.15.0 in /usr/local/lib/python3.10/site-packages (from tg) (0.15.0)
Installing collected packages: tg
Successfully installed tg-0.19.0
[BEEDELLROKEJULIANLOCKHART@BEEDELLROKEJULIANLOCKHART /]$ tg
bash: /usr/local/bin/tg: No such file or directory
[BEEDELLROKEJULIANLOCKHART@BEEDELLROKEJULIANLOCKHART /]$
```
