### ISSUE TITLE
Error executing tg

### ISSUE THREAD

**Issue by navakelvin** [paul-nameless/tg#289]
I have tried installing tg using pip3 and using the source code. In both cases I get an error when trying to open tg after typing my phone number.

What I get. How to solve it?

```shell
find: ‘/home/kelvin/.cache/tg/files’: The file or directory does not exist
Traceback (most recent call last):
  File "/home/kelvin/.local/bin/./tg", line 8, in <module>
    sys.exit(main())
  File "/home/kelvin/.local/lib/python3.10/site-packages/tg/__main__.py", line 60, in main
    tg = Tdlib(
  File "/home/kelvin/.local/lib/python3.10/site-packages/telegram/client.py", line 136, in __init__
    self._tdjson = TDJson(library_path=library_path, verbosity=tdlib_verbosity)
  File "/home/kelvin/.local/lib/python3.10/site-packages/telegram/tdjson.py", line 27, in __init__
    self._build_client(library_path, verbosity)
  File "/home/kelvin/.local/lib/python3.10/site-packages/telegram/tdjson.py", line 34, in _build_client
    self._tdjson = CDLL(library_path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by navakelvin** [comment]
Apparently it was a problem with libssl.so.1.1

Solved by:
```shell
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.16_amd64.deb
sudo dpkg -i libssl1.1_1.1.1l-1ubuntu1.6_amd64.deb
```

I was able to enter the telegram security code. However, now there is the problem that the terminal shows nothing at all when running tg.
![image](https://user-images.githubusercontent.com/77164639/192960079-37074421-8637-4306-8fa6-e9dd552030a4.png)

**Comment by yurenchen000** [comment]
update dead link

http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.17_amd64.deb
