### ISSUE TITLE
Libssl ERROR: No such file or directory error when launching tg 

### ISSUE THREAD

**Issue by aleeessio** [paul-nameless/tg#301]
I think that's a problem with libssl version. The 1.1 is no longer supported, the script should be updateo to the 3.08
```
root@d33357df4709:~# tg
Traceback (most recent call last):
  File "/usr/local/bin/tg", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/tg/__main__.py", line 60, in main
    tg = Tdlib(
  File "/usr/local/lib/python3.10/dist-packages/telegram/client.py", line 136, in __init__
    self._tdjson = TDJson(library_path=library_path, verbosity=tdlib_verbosity)
  File "/usr/local/lib/python3.10/dist-packages/telegram/tdjson.py", line 27, in __init__
    self._build_client(library_path, verbosity)
  File "/usr/local/lib/python3.10/dist-packages/telegram/tdjson.py", line 34, in _build_client
    self._tdjson = CDLL(library_path)
  File "/usr/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libssl.so.1.1: cannot open shared object file: No such file or directory
find: ‘/root/.cache/tg/files’: No such file or directory
```

**Comment by Bilalharoon** [comment]
The path is correct
```python

>>> import pkg_resources
>>> print(pkg_resources.resource_filename('telegram', 'lib/linux/libtdjson.so'))
/home/username/.local/lib/python3.10/site-packages/telegram/lib/linux/libtdjson.so
```
for whatever reason the TDLIB variable in the config file was returning null in `__main__.py`  I tried passing the path manually in main but I still get the error

**Comment by Bilalharoon** [comment]
I am getting the same error. Why do you think it is a problem with libssl?

**Comment by Bilalharoon** [comment]
I compiled my own `tdlibjson.so` using this [website](https://tdlib.github.io/td/build.html?language=Python) then put the path to that as the `tdlib_path` in the config file. I got and api error but that seemed to fix the libssl issue.
