### ISSUE TITLE
OSError, wrong ELF class: ELFCLASS64 after installing with pip.

### ISSUE THREAD

**Issue by Kreijstal** [paul-nameless/tg#302]
tg: 
```

Traceback (most recent call last):
  File "/home/pi/.local/bin/tg", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.9/site-packages/tg/__main__.py", line 60, in main
    tg = Tdlib(
  File "/home/pi/.local/lib/python3.9/site-packages/telegram/client.py", line 136, in __init__
    self._tdjson = TDJson(library_path=library_path, verbosity=tdlib_verbosity)
  File "/home/pi/.local/lib/python3.9/site-packages/telegram/tdjson.py", line 27, in __init__
    self._build_client(library_path, verbosity)
  File "/home/pi/.local/lib/python3.9/site-packages/telegram/tdjson.py", line 34, in _build_client
    self._tdjson = CDLL(library_path)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/pi/.local/lib/python3.9/site-packages/telegram/lib/linux/libtdjson.so: wrong ELF class: ELFCLASS64
find: ‘/home/pi/.cache/tg/files’: No such file or directory
```

**Comment by paul-nameless** [comment]
Hi, you can find x86 builds of tdlib for linux here: https://github.com/ForNeVeR/tdlib.native/releases

**Comment by Kreijstal** [comment]
what about arm builds? or just tell pip to compile

**Comment by paul-nameless** [comment]
tdlib compilation not a fast process it is better to find recent builds somewhere or build from sources
